Docs: nuxt examples
Dokploy/examples pull request #6
Opened 2024-11-12 14:45 UTC by StefanVDWeide

I've added examples for deploy a Nuxt site both with server side rendering and as a static stite. Also, solved an issue with the VueJS docs where the wrong start command was written down.

2024-11-13 12:34 UTC, mezotv commented
I dont think setting the port to 80 is required for this. Any port should work since it runs in a container anyways.

2024-11-13 17:47 UTC, StefanVDWeide commented
> I dont think setting the port to 80 is required for this. Any port should work since it runs in a container anyways.

80 is the default port for NGINX which serves the files in this case. Setting it to anything else will result in a bad gateway error. I've tested 3000 and 81 just in case.

2024-11-13 17:51 UTC, mezotv commented
> > I dont think setting the port to 80 is required for this. Any port should work since it runs in a container anyways.
> 
> 80 is the default port for NGINX which serves the files in this case. Setting it to anything else will result in a bad gateway error. I've tested 3000 and 81 just in case.

Oh so thats only an internal port then?

2024-11-13 18:12 UTC, StefanVDWeide commented
> > > I dont think setting the port to 80 is required for this. Any port should work since it runs in a container anyways.
> > 
> > 
> > 80 is the default port for NGINX which serves the files in this case. Setting it to anything else will result in a bad gateway error. I've tested 3000 and 81 just in case.
> 
> Oh so thats only an internal port then?

Yeah exactly, since the container exposes port 80 the domain needs to be configured to point there

2024-11-14 05:53 UTC, Siumauricio commented
I tested and both works, awesome

Can you change npm to pnpm? is more fast than npm

2024-11-14 05:53 UTC, Siumauricio requested changes

2024-11-14 05:53 UTC, Siumauricio commented on nuxt/README.md
> +3. **Set the publish publish directory**:
```suggestion
3. **Set the publish directory**:
```

2024-11-15 11:03 UTC, StefanVDWeide commented
> I tested and both works, awesome
> 
> Can you change npm to pnpm? is more fast than npm

Great! Changed the example to `pnpm`

2024-11-15 13:07 UTC, mezotv commented
> Great! Changed the example to `pnpm`

With pnpm you can drop the run so its just `pnpm generate`

2024-11-17 15:43 UTC, Siumauricio commented
@StefanVDWeide I still see the package lock file, can you please run pnpm install to generate the pnpm lock file and delete the package.lock.json?

2024-11-18 13:57 UTC, StefanVDWeide commented
> @StefanVDWeide I still see the package lock file, can you please run pnpm install to generate the pnpm lock file and delete the package.lock.json?

Ahh I see. I thought you meant to update the instructions. I've gone ahead and ran install with `pnpm` and remove the old lock file!

2024-11-18 14:10 UTC, Siumauricio approved these changes
Thanks!

2024-11-18 14:10 UTC, merged

2025-07-02 16:51 UTC, codeflorist commented
This says `merged`, but there's no nuxt example in current repo?